cookie:
  expiry_days: 30
  key: avisos_mantenimiento_cookie_key_2026
  name: avisos_mantenimiento_cookie

credentials:
  usernames:
    jaime:
      email: jaime@local.com
      first_name: Jaime
      last_name: Supervisor
      password: jaime1234
    luisreina:
      email: luisreina@local.com
      first_name: Luis
      last_name: Reina
      password: luis1234
    gustavo:
      email: gustavo@local.com
      first_name: Gustavo
      last_name: Supervisor
      password: gustavo1234
    fran:
      email: fran@local.com
      first_name: Fran
      last_name: Coordinador
      password: fran1234
    andres:
      email: andres@local.com
      first_name: Andrés
      last_name: Coordinador
      password: andres1234
    jonatan:
      email: jonatan@local.com
      first_name: Jonatan
      last_name: Coordinador
      password: jonatan1234
    laura:
      email: laura@local.com
      first_name: Laura
      last_name: Coordinadora
      password: laura1234

pre-authorized:
  emails: []